### ISSUE TITLE
Creating JIRA Issue Results in 404 Forbidden

### ISSUE THREAD

**Issue by nicolas-HORST** [atlassian/atlascode#552]
**Describe the bug**
When trying to create an Issue with // TODO: it opens a new tab within VS Code and displays a HTML message that looks like the following image when parse correctly (the text is in german)

<img width="722" height="350" alt="Image" src="https://github.com/user-attachments/assets/0a3b3552-7109-494b-a5b4-40479f1e48da" />

**To Reproduce**
1. Go to a File within a Directory
2. Write // TODO:, it will display a message to create a JIRA issue
3. Click on it
4. A new tab appears with the error message
5. When scrolling all the way down, I can see that I could select a site but its empty

<img width="803" height="338" alt="Image" src="https://github.com/user-attachments/assets/530ec171-ec14-43b8-8afc-77ffad0098df" />

I am in multiple JIRA environments so I might not have the permissions to create an issue in one other instance. I see that there are some other JIRA sites listed in the error message.

I think it is because of a single JIRA environment that is missing the permissions. Because in the error message I can only see this instance.

**Expected behavior**
It should not error and I should be able to create a JIRA issue on a site

**Screenshots**
See above screenshots

**Environment and Version (please complete the following information):**
 - Atlassian Plugin Version (3.8.6) 
 - Visual Studio Code Version (1.202.0 (user setup)) 
 - Version: 1.102.0 (user setup)
    Commit: cb0c47c0cfaad0757385834bd89d410c78a856c0
    Date: 2025-07-09T22:10:34.600Z
    Electron: 35.6.0
    ElectronBuildId: 11847422
    Chromium: 134.0.6998.205
    Node.js: 22.15.1
    V8: 13.4.114.21-electron.0
    OS: Windows_NT x64 10.0.19045
 - Is this a local or cloud environment? (JIRA Cloud, Local VS Code) 
 - If Cloud, Browser (edge)
 - If Local, OS (Windows 10 22H2)

**Additional context**
As I don't know if the error message contains sensitive information like apiKeys or whatnot I cannot upload it.

**Comment by marcomura** [comment]
Thanks for reporting this issue, @nicolas-HORST .

We are currently working on a bug fix that will prevent projects without write-permissions to be selected for creating new issue.
I think this is going to solve this bug as well.

**Comment by nicolas-HORST** [comment]
@marcomura 
Great! I'd be happy to test it if you want to pre release the version before releasing it

**Comment by marcomura** [comment]
That would be awesome, thanks @nicolas-HORST .

I'll let you know when this fix is available in a pre-release version!

**Comment by nicolas-HORST** [comment]
Hi, just as an input I still have the Error and also Im Getting Forbidden 403 in the Menu, whenever I click on the [Bitbucket: Nicolas] bar button. (Within the Atlassian Settings Page under Bitbucket)
